# Generated by Django 4.2.6 on 2023-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
