# Generated by Django 4.2.6 on 2023-12-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_music_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="Typeof",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.AlterField(
            model_name="music",
            name="artist",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="music",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="static/files"),
        ),
        migrations.AlterField(
            model_name="music",
            name="image",
            field=models.ImageField(upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="music",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
