# Generated by Django 4.2.6 on 2023-12-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_music_typeof_alter_music_artist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_name", models.CharField(max_length=20)),
                ("album_image", models.FileField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=20)),
                ("song", models.FileField(upload_to="songs")),
                ("picture", models.FileField(upload_to="picture")),
                ("singer", models.CharField(max_length=20)),
                (
                    "album_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.album"
                    ),
                ),
            ],
        ),
    ]
