# Generated by Django 4.2.6 on 2023-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_album_songs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_image",
            field=models.FileField(upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="songs",
            name="picture",
            field=models.FileField(upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="songs",
            name="song",
            field=models.FileField(upload_to="static/files"),
        ),
    ]
